### ISSUE TITLE
Installer fails on arm64 (Raspberry Pi Running 64 Bit Raspberry Pi OS)

### ISSUE THREAD

**Issue by Underestimated** [cloudradar-monitoring/rportd-installer#9]
As referenced [here](https://github.com/cloudradar-monitoring/rport/issues/507):

> When the installer calls your deployment link, it cannot find a package of rportd for the arm64 architecture.
> I dug into your installer script and it looks like you have actually put a sed instruction in just before the download URL line that renames aarch64 to arm64, yet the only package your site will find is one for aarch64. Maybe your command was backwards by accident?
> 
>![image](https://user-images.githubusercontent.com/20806875/172594192-63e2abb8-1363-468a-b55a-da4069e21730.png)
> 
> Either way I've self solved the issue by just manually typing in aarch64 at the end of the url as you can see in the screenshot

Opened for tracking, apologies, I didn't know you'd kept the install script in another repository.

**Comment by thorstenkramm** [comment]
This issue has been resolved. 
Packages for Arm64 are now published with the suffix `aarch64` which matches `uname -m`.
The installer does change the architecture name any more. (The second line of the above screenshot has been removed.)

**Comment by Underestimated** [comment]
Sorry, its not fixed.
The issue is the code with the red box around it, I think you have it backwards because I have to swap it around to get it to work.

Original:
![image](https://user-images.githubusercontent.com/20806875/176112215-c0f4d9d6-1642-467a-8ea1-6715ce7bef94.png)

Working (after my edit):
![image](https://user-images.githubusercontent.com/20806875/176112903-d4b87ca7-14dd-4164-962a-6d9930d0756c.png)

I think you're expecting any instance of arm64 to change to aarch64 but instead it's taking aarch64 and making it arm64, as there are no arm64 packages in your repository, the installer just fails with a "this is the latest version" message. (or on a new install the default no package message)

**Comment by thorstenkramm** [comment]
The first screenshot seems outdated.
The installer does not change the output of `uname -m` any more. [See changes](https://github.com/cloudradar-monitoring/rportd-installer/blob/main/snippets/installer/04-install-server.sh#L2-L5).
On Arm64 I get 
```
uname -m
aarch64
```
The URL is built correctly.
```
RELEASE=stable
ARCH=$(uname -m)
DOWNLOAD_URL="https://download.rport.io/rportd/${RELEASE}/latest.php?arch=${ARCH}"
curl -LSs "${DOWNLOAD_URL}" -o rportd.tar.gz
ls -l rportd.tar.gz
```

**Comment by Underestimated** [comment]
I'll try removing and repulling the installer package... It's still there on my copy, yet the one you have on the release page doesn't have the code.
I'm using the instruction `curl -s https://get.rport.io/update -o rportd-update.sh` as per documentation, it doesn't seem to be pulling the latest version of the script. when I ran the link from my browser, the downloaded code was also the old version too. something isn't updated on your server by the look of that

**Comment by thorstenkramm** [comment]
@Underestimated I'll fix the update script ASAP. Thanks for the hint.
